name: Playwright Tests
on:
  workflow_call:
    inputs:
      channel_id:
        description: 'The slack channel ID to send a message on failure. If this is not provided then no message is sent.'
        required: false
        default: 'NO_SLACK'
        type: string
      environment:
        description: 'Environment to run tests'
        required: false
        default: 'dev'
        type: string
      source:
        description: 'Repo triggering tests'
        required: false
        default: 'all'
        type: string
      branch:
        description: 'Branch name'
        required: false
        default: 'main'
        type: string

jobs:
  test:
    timeout-minutes: 60
    runs-on: [ self-hosted, hmpps-github-actions-runner ]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch || 'main' }}
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install playwright
        run: npx playwright install
      - name: Run Playwright tests
        id: playwright-tests
        run: npm run ${{ inputs.environment }}:${{ inputs.source }}:ci
        env:
          ORACLE_DB_USER: ${{ secrets.ORACLE_DB_USER }}
          ORACLE_DB_PASSWORD: ${{ secrets.ORACLE_DB_PASSWORD }}
          ORACLE_DB_CONNECT_STRING: ${{ secrets.ORACLE_DB_CONNECT_STRING }}
          AAP_CLIENT_ID: ${{ secrets.AAP_CLIENT_ID }}
          AAP_CLIENT_SECRET: ${{ secrets.AAP_CLIENT_SECRET }}
          ARNS_ASSESSMENT_CLIENT_ID: ${{ secrets.ARNS_ASSESSMENT_CLIENT_ID }}
          ARNS_ASSESSMENT_CLIENT_SECRET: ${{ secrets.ARNS_ASSESSMENT_CLIENT_SECRET }}
          # URLs
          DELIUS_URL: https://ndelius.test.probation.service.justice.gov.uk
          TOKEN_URL: ${{ secrets.TOKEN_URL }}
          # Credentials
          MPOP_USERNAME: ${{ secrets.E2E_MPOP_USERNAME }}
          DELIUS_USERNAME: ${{ secrets.E2E_DELIUS_USERNAME }}
          DELIUS_PASSWORD: ${{ secrets.E2E_DELIUS_PASSWORD }}

      - name: Publish Test Summary
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: 'ctrf/ctrf-report.json'
        if: always()
      
      - name: Archive screenshots & trace
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: screenshots-playwright
          path: |
            test-results/**/*
      
      - name: Slack notification
        if: failure()
        uses: slackapi/slack-github-action@v3.0.3
        env:
          SLACK_CHANNEL: ${{ inputs.channel_id }}
          REPO_NAME: ${{ github.repository }}
          SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
        with:
          method: chat.postMessage
          token: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "🚨 ${{ inputs.environment }} - Integration Playwright Tests Failed",
              "attachments": [
               {
                 "color": "#FF0000",
                 "text": ":x: *Playwright Integration tests notification*\nWorkflow failed on ${{ inputs.environment }} environment for ${{ env.REPO_NAME }}"
                }
              ]
            }